---
- name: Add Docker Key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg

- name: Add Docker Repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    update_cache: yes
    validate_certs: yes
    filename: docker.list

- name: Install Docker
  apt:
    name: docker-ce