---
- name: Set up login banner file
  copy:
    src: ../files/issue.net
    dest: /etc/issue.net
    owner: root
    group: root
    mode: 0644

- name: Configure ssh to use the login banner
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '^(#)?Banner'
    line: 'Banner /etc/issue.net'
  notify: restart ssh

- name: Set up the MOTD updater path
  file:
    name: /etc/update-motd.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Ensure the MOTD updater has the right scripts
  copy:
    src: ../files/update-motd.d/
    dest: /etc/update-motd.d/
    owner: root
    group: root
    mode: 0755

# This line thanks to:
# https://elhombrequereventodeinformacion.wordpress.com/2015/04/30/motd-handling-in-debian-jessie-fixed/
- name: Update /etc/pam.d/sshd to run the update-motd.d
  lineinfile:
    state: present
    dest: /etc/pam.d/sshd
    insertbefore: '^\s*session    optional     pam_motd.so  motd=/run/motd.dynamic\s*$'
    line: "session    optional     pam_exec.so  type=open_session stdout /bin/run-parts /etc/update-motd.d"
