---
# Based on https://docs.ceph.com/docs/master/cephadm/install/

# This takes the key from the Ubuntu Keyserver, not from the Ceph repos, 
# because their supplied key currently breaks APT.
- name: Add Ceph Key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 08B73419AC32B4E966C1A330E84AC2C0460F3994

- name: Add Ceph Repository
  apt_repository:
    repo: "deb https://download.ceph.com/debian-octopus/ {{ ansible_distribution_release }} main"
    validate_certs: yes
    filename: ceph.list
    update_cache: yes

- name: Install Ceph
  apt:
    name: ceph
    state: present

# TODO: Follow https://docs.ceph.com/docs/master/install/manual-deployment/